AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A SAM template for getting node count from Neptune graph DB.

Resources:
  MyLambdaFunction:
    Type: AWS::Serverless::Function 
    Properties:
      Handler: index.handler
      Runtime: python3.11
      CodeUri: amplify/backend/function/getGraphData
